run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - gofumpt
    - gocritic
    - revive
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - dupl

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam
  
  revive:
    rules:
      - name: use-any
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
